apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment  # Name of the application
  labels:
    app: tomcat
spec:
  selector:
    matchLabels:
      app: tomcat
  replicas: 2
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: tomcat:8.0  # Docker image
        ports:
        - containerPort: 8080
