apiVersion: v1
kind: Service
metadata:
  name: tomcat-service  # Name of the application
spec:
  type: LoadBalancer
  selector:
   app: tomcat
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080